### PR TITLE
created signup screen and form

### PR DESCRIPTION
**Pull request by EnigmaTechx**

### CODE REVIEW

**Comment by vijay010498** [comment]
@EnigmaTechx  Can you resolve the conflicts  and update ?

**Comment by EnigmaTechx** [comment]
fixed conflicts

**Review by vijay010498 — APPROVED** [review]
I made some changes to the signup form, error handling, and OTP screen.
Tested signup: All Good

**Review by KennedyGIT — APPROVED** [review]
Looks good !

**Review by ChristinaTresa — APPROVED** [review]

**Review by KennedyGIT — APPROVED** [review]

**Pull request merged**
